### ISSUE TITLE
recognize multiline strings as strings?

### ISSUE THREAD

**Issue by oren-zohar** [open-policy-agent/opa-idea-plugin#121]
# What would you like to be added
not sure if it's a missing configuration on my IDE settings or the plugin but it doesn't highlight rego multiline strings as the double quotes strings: 

![image](https://user-images.githubusercontent.com/85433724/147405172-c8e7d533-2e1c-4b7d-a80b-1a2dfef92ed1.png)

**Comment by vgramer** [comment]
Hi, thanks for reporting this issue. I will implement it :)

**Comment by stevend-15** [comment]
Are there any other ways to write a multi-line string other than using backticks? I find them quite bothersome for testing because _everything_ must be exactly the same between the rule output and testing equality string. 

I would specifically like to use them in a 'default' assignment. Using 'sprintf' throws an error. 

Any help is appreciated

**Comment by anderseknert** [comment]
@stevend-15 is anything about that specific to the IDEA plugin, or you're just talking about how OPA works in general?

If you could provide an example of where you think backtick-strings doesn't work like you'd want them to, I'd be happy to take a look.

**Comment by stevend-15** [comment]
I believe that I'm talking about how OPA works in general. My example is as below and follows the AWS control linked below: 
https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html#fsbp-ec2-19

```
package example

default deny := `EC2.19 failed: found a security group ingress with a 
    high risk port that allows unrestricted access (0.0.0.0/0 or ::/0)`

deny := "EC2.19 passed" {
    #some rules go here
}
```

The above code snippet will run and produce the desired policy. However, when doing unit tests, my string comparison must be EXACTLY like the raw string above. Ex: 

```
package example

import data.example.deny

test_deny {
    deny == `EC2.19 failed: found a security group ingress with a 
    high risk port that allows unrestricted access (0.0.0.0/0 or ::/0)`
    with input as {
    ....
}
```

Any deviation whatsoever will result in a failed test, and keeping the rigid raw string consistent with line length and indentation standards is difficult at best.

**Comment by anderseknert** [comment]
Right, but is that not more a consequence of using strict equality (`==`) for your assertions rather than something less exact/strict? Some alternatives could be:
```
contains(deny, "high risk port") with input as {}

startswith(deny, "EC2.19 failed") with input as {}

regex.match(`EC2\.19 failed: .*`, deny)
```

Or if you _do_ want exact matching for everything but line breaks / whitespace, a little helper function to normalize both before comparison would do the trick. I normally use [this](https://github.com/anderseknert/rego-test-assertions) little helper library, and I could easily imagine adding more helpful methods to that if it would help.

**Comment by stevend-15** [comment]
You're absolutely correct - my issue is certainly a consequence of the strict equality. I did not think of those built-ins to use with testing. It seems to me that they can be a 'lazy' test of equality of sorts. 

Is that assertion framework anywhere in the docs? After a double take I did not see it anywhere. Perhaps it's not fully ready for deployment?

**Comment by stevend-15** [comment]
I see. I think that library will certainly come in handy when testing and I will certainly use it. 

On a side note, my VSCode editor still does not colorize the raw strings:

<img width="440" alt="image" src="https://user-images.githubusercontent.com/66806985/178339331-c51cf84f-3932-4d4b-93fc-510cf21773c2.png">

Just to confirm: those backticks are the only way to create multi-line strings?

**Comment by anderseknert** [comment]
Yep, that looks like an oversight in the VS Code plugin. Feel free to open [an issue](https://github.com/open-policy-agent/vscode-opa)!

As for multiline strings, yeah that's how you'd normally do it. I suppose you could [concat](https://www.openpolicyagent.org/docs/latest/policy-reference/#builtin-strings-concat) an array of strings with `"\n"`as the delimiter too if you wanted to build it programatically.
